# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20180522_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publish_year',
            field=models.SmallIntegerField(default=datetime.datetime(2018, 5, 22, 16, 31, 15, 418209, tzinfo=utc)),
        ),
    ]
