# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20180522_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publish_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
