# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20180522_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=100, null=True),
        ),
    ]
