# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_publication_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
