# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
