# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sponsored', models.CharField(max_length=256)),
                ('principal_investigator', models.CharField(max_length=100)),
                ('start_year', models.SmallIntegerField()),
                ('end_year', models.SmallIntegerField(blank=True)),
            ],
        ),
    ]
