# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default='No Title', max_length=100, null=True),
        ),
    ]
