# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_auto_20180525_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('course_type', models.CharField(choices=[('UG', 'Undergraduate'), ('G', 'Graduate')], max_length=2)),
                ('start_year', models.SmallIntegerField()),
                ('end_year', models.SmallIntegerField(blank=True)),
                ('semester', models.CharField(blank=True, max_length=25)),
                ('acitve', models.BooleanField()),
            ],
        ),
    ]
