# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='acitve',
            new_name='active',
        ),
    ]
